import LoginForm from "./Form/LoginForm";
import SignupForm from "./Form/SignupForm";
import Template from "./Form/Template";
import AdminForm from "./Form/AdminForm";
import Input from "./Input";
import Protected from "./AuthLayout/AuthLayout";
import ProtectedAdmin from "./AuthLayout/AdminAuthLayout";
import Button from "./Button";
import TextArea from './TextArea'
import Select from '../components/Select'
import LottieAnimation from "./LottieAnimation";
import ProductSection from "./Product/ProductSection";
import ForgotPasswordForm from "./Form/ForgotPasswordForm";
import RadioButton from "./RadioButton";
import BgFillButton from "./BgFillButton";
import FileInput from "./FileInput";
import CheckboxInput from "./CheckboxInput";
import Loading from "./Loading";
import Header from "./Header/Header"
import Footer from "./Footer/Footer"
export { LoginForm, SignupForm, Template, AdminForm, Input, Protected, ProtectedAdmin, Button, TextArea, Select, LottieAnimation, ProductSection, ForgotPasswordForm, RadioButton, BgFillButton, FileInput, CheckboxInput, Loading, Header, Footer }